name: Rust build

on: 
  push:
    tags-ignore:
      - '*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Build
          run: |
            echo -e "[url \"https://github.com/\"]\n\tinsteadOf = ssh://git@github.com/" > ~/.gitconfig
            mkdir -p build
            rustup default nightly && cargo install wasm-pack && yarn install && yarn build
