name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - uses: actions/labeler@v2
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
        - name: Build
          run: |
            echo -e "[url \"https://github.com/\"]\n\tinsteadOf = ssh://git@github.com/" > ~/.gitconfig
            rustup default nightly && cargo install wasm-pack && yarn install && yarn build
            
